package com.cn.ac.tools;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class UnicodeDataGenerator {

    public static void main(String[] args) throws Exception {
        String targetDir = "ac-core/src/main/java/com/cn/ac/internal";
        if (args.length > 0) {
            targetDir = args[0];
        }
        File outDir = new File(targetDir);
        outDir.mkdirs();

        generateSimpleCaseFold(new File(outDir, "SimpleCaseFoldData.java"));
        generateUnicodeProps(new File(outDir, "UnicodePropsData.java"));
        System.out.println("Unicode data generation completed successfully.");
    }

    private static void generateSimpleCaseFold(File file) throws Exception {
        List<Integer> srcList = new ArrayList<>();
        List<Integer> dstList = new ArrayList<>();

        for (int cp = 128; cp <= 0x10FFFF; cp++) {
            int lower = Character.toLowerCase(cp);
            if (lower != cp) {
                srcList.add(cp);
                dstList.add(lower);
            }
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println("package com.cn.ac.internal;");
            pw.println();
            pw.println("import java.util.Arrays;");
            pw.println();
            pw.println("// Auto-generated by UnicodeDataGenerator. Do not edit manually.");
            pw.println("public final class SimpleCaseFoldData {");
            pw.println("    public static final String UNICODE_VERSION = \"17.0.0\";");
            pw.println();
            pw.println("    private static final int[] SRC = new int[] {");
            writeArray(pw, srcList);
            pw.println("    };");
            pw.println();
            pw.println("    private static final int[] DST = new int[] {");
            writeArray(pw, dstList);
            pw.println("    };");
            pw.println();
            pw.println("    public static int fold(int codePoint) {");
            pw.println("        if (codePoint < 128) {");
            pw.println("            if (codePoint >= 'A' && codePoint <= 'Z') {");
            pw.println("                return codePoint + 32;");
            pw.println("            }");
            pw.println("            return codePoint;");
            pw.println("        }");
            pw.println("        int idx = Arrays.binarySearch(SRC, codePoint);");
            pw.println("        return idx >= 0 ? DST[idx] : codePoint;");
            pw.println("    }");
            pw.println();
            pw.println("    private SimpleCaseFoldData() {}");
            pw.println("}");
        }
    }

    private static void generateUnicodeProps(File file) throws Exception {
        // Collect intervals of (start, end) for Unicode Alnum and Whitespace
        List<Integer> alnumRanges = new ArrayList<>();
        int alnumStart = -1;
        int prevAlnum = -1;

        List<Integer> wsRanges = new ArrayList<>();
        int wsStart = -1;
        int prevWs = -1;

        for (int cp = 0; cp <= 0x10FFFF; cp++) {
            boolean isAlnum = isAlnumChar(cp);
            if (isAlnum) {
                if (alnumStart == -1) {
                    alnumStart = cp;
                }
                prevAlnum = cp;
            } else {
                if (alnumStart != -1) {
                    alnumRanges.add(alnumStart);
                    alnumRanges.add(prevAlnum);
                    alnumStart = -1;
                }
            }

            boolean isWs = isWhitespaceChar(cp);
            if (isWs) {
                if (wsStart == -1) {
                    wsStart = cp;
                }
                prevWs = cp;
            } else {
                if (wsStart != -1) {
                    wsRanges.add(wsStart);
                    wsRanges.add(prevWs);
                    wsStart = -1;
                }
            }
        }
        if (alnumStart != -1) {
            alnumRanges.add(alnumStart);
            alnumRanges.add(prevAlnum);
        }
        if (wsStart != -1) {
            wsRanges.add(wsStart);
            wsRanges.add(prevWs);
        }

        try (PrintWriter pw = new PrintWriter(new FileWriter(file))) {
            pw.println("package com.cn.ac.internal;");
            pw.println();
            pw.println("// Auto-generated by UnicodeDataGenerator. Do not edit manually.");
            pw.println("public final class UnicodePropsData {");
            pw.println("    public static final String UNICODE_VERSION = \"17.0.0\";");
            pw.println();
            pw.println("    private static final int[] ALNUM_RANGES = new int[] {");
            writeArray(pw, alnumRanges);
            pw.println("    };");
            pw.println();
            pw.println("    private static final int[] WS_RANGES = new int[] {");
            writeArray(pw, wsRanges);
            pw.println("    };");
            pw.println();
            pw.println("    public static boolean isUnicodeAlnum(int cp) {");
            pw.println("        return binarySearchRange(ALNUM_RANGES, cp);");
            pw.println("    }");
            pw.println();
            pw.println("    public static boolean isWhitespace(int cp) {");
            pw.println("        return binarySearchRange(WS_RANGES, cp);");
            pw.println("    }");
            pw.println();
            pw.println("    private static boolean binarySearchRange(int[] ranges, int cp) {");
            pw.println("        int low = 0;");
            pw.println("        int high = (ranges.length / 2) - 1;");
            pw.println("        while (low <= high) {");
            pw.println("            int mid = (low + high) >>> 1;");
            pw.println("            int start = ranges[mid * 2];");
            pw.println("            int end = ranges[mid * 2 + 1];");
            pw.println("            if (cp < start) {");
            pw.println("                high = mid - 1;");
            pw.println("            } else if (cp > end) {");
            pw.println("                low = mid + 1;");
            pw.println("            } else {");
            pw.println("                return true;");
            pw.println("            }");
            pw.println("        }");
            pw.println("        return false;");
            pw.println("    }");
            pw.println();
            pw.println("    private UnicodePropsData() {}");
            pw.println("}");
        }
    }

    private static boolean isAlnumChar(int cp) {
        int type = Character.getType(cp);
        return type == Character.UPPERCASE_LETTER ||
                type == Character.LOWERCASE_LETTER ||
                type == Character.TITLECASE_LETTER ||
                type == Character.MODIFIER_LETTER ||
                type == Character.OTHER_LETTER ||
                type == Character.NON_SPACING_MARK ||
                type == Character.COMBINING_SPACING_MARK ||
                type == Character.ENCLOSING_MARK ||
                type == Character.DECIMAL_DIGIT_NUMBER ||
                type == Character.CONNECTOR_PUNCTUATION;
    }

    private static boolean isWhitespaceChar(int cp) {
        int type = Character.getType(cp);
        return type == Character.SPACE_SEPARATOR ||
                type == Character.LINE_SEPARATOR ||
                type == Character.PARAGRAPH_SEPARATOR ||
                (cp >= 0x0009 && cp <= 0x000D) ||
                cp == 0x0085 ||
                cp == 0x00A0 ||
                cp == 0x1680 ||
                (cp >= 0x2000 && cp <= 0x200A) ||
                cp == 0x2028 ||
                cp == 0x2029 ||
                cp == 0x202F ||
                cp == 0x205F ||
                cp == 0x3000;
    }

    private static void writeArray(PrintWriter pw, List<Integer> list) {
        int count = 0;
        pw.print("        ");
        for (int i = 0; i < list.size(); i++) {
            pw.print(list.get(i));
            if (i < list.size() - 1) {
                pw.print(", ");
            }
            count++;
            if (count % 16 == 0 && i < list.size() - 1) {
                pw.println();
                pw.print("        ");
            }
        }
        pw.println();
    }
}
