package com.cn.ac.exception;

public enum AcErrorCode {
    NULL_KEYWORD,
    EMPTY_KEYWORD,
    EMPTY_AFTER_TRANSFORM,
    NEGATIVE_KEYWORD_ID,
    DUPLICATE_KEYWORD_ID,
    DUPLICATE_NORMALIZED_KEYWORD,
    INVALID_SURROGATE,
    MAX_KEYWORDS_EXCEEDED,
    MAX_KEYWORD_LENGTH_EXCEEDED,
    MAX_TOTAL_CODE_POINTS_EXCEEDED,
    MAX_STATES_EXCEEDED,
    MAX_EDGES_EXCEEDED,
    MAX_OUTPUTS_EXCEEDED,
    INTEGER_OVERFLOW,
    UNSUPPORTED_CONFIG,
    CORRUPT_AUTOMATON,
    SNAPSHOT_VERSION_MISMATCH,
    UNICODE_VERSION_MISMATCH,
    CHECKSUM_MISMATCH
}
